---
title: "Lab 2: Getting Started With Homework"
subtitle: Biostat 203B
author: "Dr. Hua Zhou @ UCLA"
date: today
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
    link-external-icon: true
    link-external-newwindow: true
comments:
  hypothesis: true
knitr:
  opts_chunk: 
    echo: true
    fig.align: 'center'
---

This tutorial assumes that you have already installed R, RStudio, and Git on your computer. If not, please refer to the [Lab 1](https://ucla-biostat-203b.github.io/2026winter/labs/lab01/lab01.html).

# Set up GitHub repo for 203B homework

- On <https://github.com/>, create a **private** repository `biostat-203b-2026-winter` and add `Hua-Zhou` and TA team (`BowenZhang2001` for Lec 1; `Tomoki-Okuno` and `yucais` for Lec 82) as your collaborators with write permission. This repository is for submitting your 203B homework.

- You can use RStudio to git clone the `biostat-203b-2026-winter` repository to your local machine: `File` -> `New Project...` -> `Version Control` -> `Git` -> input `Repository URL:`, `Project directory name:` (203b-hw).

- Alternatively, in Terminal (Mac Terminal, Windows WSL, Windows Git Bash), you can run
```{bash}
#| eval: false
git clone [SSH_ADDRESS] ~/203b-hw
```
to clone your homework repository to a folder called `203b-hw` under your home directory on your computer. `[SSH_ADDRESS]` is obtained by clicking the menu `<> Code` -> `SSH` on the repository page on GitHub. Then you can double click the `biostat-203b-2026-winter.Rproj` file to open the RStudio project.

# MIMIC Data

Much of homework and exercises are demonstrated on the [MIMIC-IV](https://physionet.org/content/mimiciv/3.1/) v3.1 data set. Download the data to your computer (10.66 GB), and make it available at `~/mimic`. For example, you can create a symbolic link by
```{bash}
#| eval: false
ln -s /PATH/TO/YOUR/MIMIC_FOLDER ~/mimic
```
Your homework solution should always read MIMIC data from `~/mimic`. This is critical for TA team to reproduce your homework.
```{bash}
ls -l ~/mimic/
```

::: {.callout-tip}
## Access Box folder on Windows from WSL 

If you put MIMIC data in Box and access it using `Box Drive` program on Windows, you'll find that you cannot read that folder from WSL. You can resolve it following instructions in this [issue](https://github.com/microsoft/WSL/issues/4310) or simply copy MIMIC data from Box to your regular Windows file system.

:::

# Start with homework 1

On your local machine: 

- Clone the repository, create `develop` branch, where your work on solutions. Useful git commands:

```{bash}
#| eval: false

# clone the project
git clone git@github.com:[USERNAME]/biostat-203b-2026-winter.git
# enter project folder
cd biostat-203b-2026-winter
# what branches are there?
git branch
# create develop branch
git branch develop
# switch to the develop branch
git checkout develop
# create folder for HW1
mkdir hw1
cd hw1
# let's write solutions
echo "sample solution" > hw1.Rmd
echo "some bug" >> hw1.Rmd
# commit the code
git add hw1.Rmd
git commit -m "start working on problem #1"
# push to remote repo
git push
```

- Submit and tag HW1 solution to the `main` branch. Useful git commands:

```{bash}
#| eval: false

# which branch are we in?
git branch
# change to the main branch
git checkout main
# merge develop branch to main branch
# git pull origin develop 
git merge develop
# push to the remote main branch
git push
# tag version hw1
git tag hw1
git push --tags
```

- RStudio has good Git integration. But practice command line operations also.

# Homework 1

- Demo Q2, Q3.1, Q3.2, Q5, Q6.

# Grading guideline

Your submission will graded according to this [guideline](https://github.com/ucla-biostat-203b/2026winter/blob/main/hw/hw1/grade_hw1.md).